### ISSUE TITLE
Slack add reaction shows empty box

### ISSUE THREAD

**Issue by michaelshum** [charkour/react-reactions#123] opened 2022-02-28 00:11 UTC
The default "add reaction" button (SlackSelector) in SlackCounterGroup is an empty box even after downloading fonts/slack-icons-Regular.ttf and fonts/slack-icons-Regular.woff in public/.

<img width="88" alt="empty" src="https://user-images.githubusercontent.com/3534397/155905967-dce5b8dd-28ec-4fc0-958a-062b55106874.png">

However, it shows up after clicking the SlackSelector:
<img width="93" alt="with reaction" src="https://user-images.githubusercontent.com/3534397/155906004-357e83be-4e0c-47c5-a7fe-7dcbb33dc56d.png">

Is there something else we need to do to include the emoji?

**Expected behavior**
I would expect the add reaction button to include required fonts without selecting the SlackSelector.

**Screenshots**
Included in-line

**Desktop (please complete the following information):**
 - macOS
 - Chrome
 - Version 98.0.4758.102 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
- N/A

**Comment by charkour** [comment] 2022-02-28 02:42
Hey @michaelshum, thanks for reporting this! 

Could you provide a stackblitz or code sandbox with the reproduced issue? That will help me quickly diagnose the issue. Thanks!

**Comment by michaelshum** [comment] 2022-02-28 05:38
Hey @charkour, here (https://codesandbox.io/s/optimistic-ully-gdmxd4?file=/pages/reactions.js) is a code sandbox with this issue, as well as the one I mentioned in https://github.com/charkour/react-reactions/issues/120. 

In https://gdmxd4.sse.codesandbox.io/reactions you can see this issue: empty box before clicking, then after clicking it has the reaction emoji.

In https://gdmxd4.sse.codesandbox.io/subfolder/reactions you can see the other issue it is an empty box before and after clicking. You can also see that the SlackSelector header is also a row of empty boxes in this case.

**Comment by charkour** [comment] 2022-02-28 12:26
Perfect. Thank you! I can take a look soon.

**Comment by michaelshum** [comment] 2022-03-05 08:04
Hey @charkour, adding to this issue as I assume they're related: on Safari on iOS the default box is a maple leaf instead of an empty box
<img width="70" alt="image" src="https://user-images.githubusercontent.com/3534397/156874565-9849cab7-ade5-40a9-a0fb-0420802ca632.png">

**Comment by charkour** [comment] 2022-03-05 15:43
Haha very interesting. Seems to be a bug. I have some time today and will work on a fix. Thanks for reporting!

**Comment by charkour** [comment] 2022-03-07 03:38
I tried to fix it and released version 0.6.2, but that did not seem to work. I updated the version on CodeSandbox and it breaks it even more.

**Comment by charkour** [comment] 2022-03-07 03:38
Will continue to try to get it to work.

**Comment by charkour** [comment] 2022-03-07 04:21
Thanks for your patience. This was fixed in [v0.6.3](https://www.npmjs.com/package/@charkour/react-reactions/v/0.6.3) to include the Slack fonts in both the Counter and Selector component. 

Thanks for reporting the issue!

**Closed by charkour** 2022-03-07 04:21 UTC
Labels: bug

**Comment by michaelshum** [comment] 2022-03-07 04:57
Hey @charkour, thanks for the update. However now I'm getting that the emoji selection window doesn't have any emojis? Attaching a screenshot below:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/3534397/156970555-d1719279-e30c-4106-bb39-6736f0cec099.png">

**Comment by charkour** [comment] 2022-03-07 05:03
Oh yes. I knew something looked off. 

Thanks, I can take a look tomorrow unless you'd like to!

**Comment by charkour** [comment] 2022-03-07 14:58
Note to self: I think it has to do with the SlackCSS component. It should be separated into one that is for the Selector and one that is for the Fonts

**Comment by charkour** [comment] 2022-03-08 03:43
A fix was released in [v0.6.4](https://www.npmjs.com/package/@charkour/react-reactions/v/0.6.4). It was a regression I have naively caused in v0.6.2. Sorry and thanks for reporting!

**Comment by michaelshum** [comment] 2022-03-08 06:19
Thanks @charkour! Works for me now 🙏

One related item I asked about in https://github.com/charkour/react-reactions/issues/120#issuecomment-1053749740 is that  for files using SlackSelector in subdirectories (eg /subdir), I need to make a copy of the font files in my public folder (eg /public/subdir/fonts/slack-icons-Regular.ttf) to have it render properly. (Separately, I'm also making a copy of these files in /public/fonts).

I'm using Next.js - could this be a quirk of the framework, or am I missing the right way to import fonts correctly? Thanks very much.

**Comment by charkour** [comment] 2022-03-08 13:16
Unfortunately, that's currently the right solution. When I ported over the old react reactions lib, it handled fronts this way. In the future, I'll aim to make it easier to use!

Sorry for the current inconvenience, but that's the proper way for now.
