### ISSUE TITLE
reaction labels are not showing while using overflow-x to hidden

### ISSUE THREAD

**Issue by the-wrong-guy** [charkour/react-reactions#53] opened 2021-03-07 13:50 UTC
Hey, can you check this bug where you give `overflow property hidden` to the `parent div ` and the `labels` on the emoji `stop showing `

https://codesandbox.io/s/sweet-joliot-tzkuw?file=/src/App.js

And also can you show me the files where the styles are, so I can also make a PR

**Comment by charkour** [comment] 2021-03-07 14:04
Nice catch.

The PokemonSelector uses the FacebookSelector so you should edit those styles. Here is the [FacebookSelector Reaction Bar](https://github.com/charkour/react-reactions/blob/main/src/components/facebook/FacebookSelector.tsx) and the [Reaction Bar Emoji](https://github.com/charkour/react-reactions/blob/main/src/components/facebook/FacebookSelectorEmoji.tsx). 

Thanks!

**Comment by the-wrong-guy** [comment] 2021-03-07 14:48
> Nice catch. Thanks for the reproduction on CodeSandbox.
> 
> The PokemonSelector uses the FacebookSelector so you should edit those styles. Here is the [FacebookSelector Reaction Bar](https://github.com/charkour/react-reactions/blob/main/src/components/facebook/FacebookSelector.tsx) and the [Reaction Bar Emoji](https://github.com/charkour/react-reactions/blob/main/src/components/facebook/FacebookSelectorEmoji.tsx).
> 
> Thanks!

I have made a PR, check it  if that works

**Comment by charkour** [comment] 2021-03-08 16:38
Hey @the-wrong-guy, 

I checked out the PR, but I do not think it solves your issue while wrapping the PokemonSelector inside a div with `overflow: hidden`. Just remove `overflow: hidden` and the labels will work properly. 

Why do you need to have overflow hidden? I don't think this is an issue. 

Thanks.

**Comment by charkour** [comment] 2021-03-08 16:40
If you want, I could make it so you can pass styles to the component, so you could add margin to the top of the component so then you can make sure the labels are not cut off when using overflow hidden. 

Would a prop to pass styles be helpful?

**Comment by the-wrong-guy** [comment] 2021-03-08 19:20
> If you want, I could make it so you can pass styles to the component, so you could add margin to the top of the component so then you can make sure the labels are not cut off when using overflow hidden.
> 
> Would a prop to pass styles be helpful?

Well i am making an animation like on clicking an `emoji` the `selectors` will slide in from `transform: translateX(100%) `  to `transform: translateX(0) ` and again on clicking it will slide out slide in from `transform: translateX() `  to `transform: translateX(100%) `  so i need to hide the `selectors` that's why i need to use `overflowX : hidden`

I hope you get my point, maybe you should also add that kind of animation by default, that will be much helpful to the users

**Comment by charkour** [comment] 2021-03-08 19:35
Would it be possible for you to create a demo of the problem you are experiencing with the animation? It sounds good but I cannot picture exactly what is happening.

**Comment by the-wrong-guy** [comment] 2021-03-09 06:30
Here it's  https://codesandbox.io/s/sweet-joliot-tzkuw?file=/src/styles.css

**Comment by charkour** [comment] 2021-03-09 12:39
That's awesome! Thanks. I understand now. 

I think we can fix those labels by creating the ability to pass style props to different parts of the Selector component.

**Comment by the-wrong-guy** [comment] 2021-03-09 16:00
> That's awesome! Thanks. I understand now.
> 
> I think we can fix those labels by creating the ability to pass style props to different parts of the Selector component.
> 
> Sorry I didn't understand your request at f

> That's awesome! Thanks. I understand now.
> 
> I think we can fix those labels by creating the ability to pass style props to different parts of the Selector component.
> 
> Sorry I didn't understand your request at first.
Hope you do will do it ASAP

**Comment by charkour** [comment] 2021-03-09 19:34
yes

**Comment by the-wrong-guy** [comment] 2021-03-10 08:31
> yes

Well, what props to use, cause you didn't updated the documentation

**Comment by charkour** [comment] 2021-03-10 12:32
If you're having another issue, please open another issue and we can discuss it there. Thanks.

**Comment by the-wrong-guy** [comment] 2021-03-10 13:49
> If you're having another issue, please open another issue and we can discuss it there. Tha

> If you're having another issue, please open another issue and we can discuss it there. Thanks.

Well I did that but I think you closed the issue, check your issues

**Comment by charkour** [comment] 2021-03-10 13:50
If the issue is closed then the issue has been resolved.

**Comment by charkour** [comment] 2021-03-10 13:52
#51 was resolved in version 0.4.0

**Comment by charkour** [comment] 2021-03-13 14:07
This issue is more difficult than I initially thought.

**Comment by charkour** [comment] 2021-03-13 18:05
@the-wrong-guy, does this [demo](https://codesandbox.io/s/sweet-burnell-oh5vg?file=/src/App.js) solve your problem? I added `opacity: 0;` and `pointer-events: none` to the class `PokemonSelector_Idle` and removed `overflowX: hidden` from the parent div.

Please let me know if this solves your problem and then I can close the issue.

**Comment by the-wrong-guy** [comment] 2021-03-14 07:48
> @the-wrong-guy, does this [demo](https://codesandbox.io/s/sweet-burnell-oh5vg?file=/src/App.js) solve your problem? I added `opacity: 0;` and `pointer-events: none` to the class `PokemonSelector_Idle` and removed `overflowX: hidden` from the parent div.
> 
> Please let me know if this solves your problem and then I can close the issue.

Well actually it didn't, you can see this [codesandbox](https://codesandbox.io/s/busy-glitter-9ysk2?file=/src/App.js ), they are overlapping  the button and after that, I can see the Selectors for some secs before fading out, i don't want it to show after the button

**Comment by charkour** [comment] 2021-03-14 14:47
Okay, thanks for the code sandbox. I understand better now what your question is. I don't have time to look into this now, but what I would do is use `overflowX: hidden` on the parent div, and when you click the button to show the Selector, then `setTimeout()` for 200ms and remove `overflowX: hidden` once the selector has slid into the location. 

I can make a demo once I have time, but that might be in a couple weeks. This is lower priority since this isn't a bug but an issue with your CSS rules.

**Comment by the-wrong-guy** [comment] 2021-03-15 18:18
> Okay, thanks for the code sandbox. I understand better now what your question is. I don't have time to look into this now, but what I would do is use `overflowX: hidden` on the parent div, and when you click the button to show the Selector, then `setTimeout()` for 200ms and remove `overflowX: hidden` once the selector has slid into the location.
> 
> I can make a demo once I have time, but that might be in a couple weeks. This is lower priority since this isn't a bug but an issue with your CSS rules.
Sure, until I will also try to solve thus

**Comment by charkour** [comment] 2021-03-22 14:13
How does [this demo](https://codesandbox.io/s/competent-curran-cn4tv?file=/src/App.js) look?

**Comment by charkour** [comment] 2021-10-03 21:23
Closing due to inactivity. I believe the previous [demo](https://codesandbox.io/s/competent-curran-cn4tv?file=/src/App.js) solves the issue.

**Closed by charkour** 2021-10-03 21:23 UTC
Labels: question
